### ISSUE TITLE
How to test Mutations and Subscription

### ISSUE THREAD

**Issue by wolfiton** [tinfoil/wormwood#10]
Hi,

I haven't seen in source code of the library any possibility to test mutations or subscriptions, is this feature available?  

If so can you offer an example?

**Comment by QuinnWilton** [comment]
We don't currently support subscriptions, but you're able to test mutations in the same way as queries. You just need to make sure that when you define the query, it is marked as a mutation:

```
mutation Register($email: String!, $password: String!) {
  Register(email: $email, password: $password) {
    id
  }
}
```
