### ISSUE TITLE
Recomendation 

### ISSUE THREAD

**Issue by wolfiton** [tinfoil/wormwood#14]
Hi,

Sorry to write off topic.
Can you recommend me a good way to learn graphql besides this book https://pragprog.com/book/wwgraphql/craft-graphql-apis-in-elixir-with-absinthe?

Thanks and I apologize again for writing this but haven't found a good resource or tutorial anywhere for phoenix 1.4.

**Comment by QuinnWilton** [comment]
That book is definitely the most complete resource available. I'd try asking for help on the Elixir slack channel if you run into issues: https://elixir-slackin.herokuapp.com/

**Comment by wolfiton** [comment]
Thank you @QuinnWilton
