### ISSUE TITLE
Loading multiple gql files in one test module

### ISSUE THREAD

**Issue by Catharz** [tinfoil/wormwood#9]
We typically group queries and mutations within the same domain together.
e.g. In our "Cart" domain, we have operations like:

- getCart
- addItemToCart
- applyCoupon

We group these together in the one CartResolver module, but the way Wormwood uses module attributes for the query and schema doesn't allow us to group the tests together in a similar way.

Is this an intentional design decision we should code around?

**Comment by AaronShea** [comment]
Hey there @Catharz, sorry for taking a while to get back to you, Tinfoil was acquired recently so things have been a bit crazy over here!

I believe this may be a case I didn't account for in the short term, the initial design was to scope 1 module to 1 document, but it sounds like the opposite might be useful for your case :)

Feel free to code around this, but I would love to discuss a way to support your use case

**Comment by QuinnWilton** [comment]
I accidentally closed the issue, sorry! I was typing a comment and misclicked :)

**Comment by QuinnWilton** [comment]
I think this is a very common use-case that we should definitely aim to support! Thank you for opening the issue.

Having chatted offline with @AaronShea a bit, I don't think there's too many concerns implementation-wise, but neither of us is sure what the DSL should look like for loading multiple queries. I'd love to hear any suggestions you have :)

I think that we have a few requirements:
- It should still be possible to load and use a single query, without assigning it a name
- When loading multiple queries, I don't think the schema should be specified for each of them. I think it's a reasonable limitation to require that all tests within a single module are against the same schema, but I'm open to discussion on this point
- It should be a compile error to load both anonymous and named queries within the same module

With that being said, one possible approach is as follows:

```elixir
defmodule MyCoolApplication.MyTestCase do
  use ExUnit.Case
  use Wormwood.GQLCase, MyCoolApplication.MyAbsintheSchema

  load_gql :get_cart, "assets/js/queries/GetCart.gql"
  load_gql :add_item_to_cart, "assets/js/queries/AddItemToCart.gql"
  
  test "GetCart succeeds" do
    assert :ok = query_gql(:get_cart)
  end

  test "AddItemToCart succeeds" do
    assert :ok = query_gql(:add_item_to_cart)
  end
end
``` 

Here, I've simply moved the schema to the `use` statement, and changed the first parameter of `load_gql` to be the name the query should be registered under. `query_gql` then optionally also takes the name of the query to run, falling back to the "anonymous query" if unspecified.

Then the current use case would look like:
```elixir
defmodule MyCoolApplication.MyTestCase do
  use ExUnit.Case
  use Wormwood.GQLCase, MyCoolApplication.MyAbsintheSchema

  load_gql "assets/js/queries/GetCart.gql"
  
  test "the query succeeds" do
    assert :ok = query_gql()
  end
end
``` 

This would be a backwards incompatible change, but I think it's a straightforward enough translation that it shouldn't be too bad to just lock behind the right deprecation warnings.

This is a rough first-stab of the problem, but I wanted to throw something out there to start the discussion.

@Catharz would this proposal address your needs? Does anyone have ideas on improving or modifying how this might look or work?

**Comment by Catharz** [comment]
> @Catharz would this proposal address your needs? Does anyone have ideas on improving or modifying how this might look or work?

Thanks for looking at this!

My first thought was to add an extra argument to `load_gql` (for the operation name), and use that to generate a unique module attribute for each operation. But I was concerned about breaking your existing API. If that's not an issue, the above would work perfectly for my use case.

**Comment by wolfiton** [comment]
This fails when you need to pass also a variable to `query_gql()`,  to filter something.

The gql function should accept `gql/2`

**Comment by QuinnWilton** [comment]
Yup, I agree :) I don't think the other arguments to the function need to be changed at all

**Comment by wolfiton** [comment]
It would be awesome to use one query and add only filters that you need to test through variables.

**Comment by scottming** [comment]
@QuinnWilton @wolfiton So, what's the final decision? Do you need pr help?

**Comment by wolfiton** [comment]
> @QuinnWilton @wolfiton So, what's the final decision? Do you need pr help?

Hi @scottming,
From my point of view, it would be awesome if you have the desire to help and also please look at adding subscriptions testing to `Wormwood` tests.

They are not supported at the moment and it is a shame because this testing library makes Graphql testing easier and more logical.

Also, I like the fact that the team has implemented the idea one test per file because it will help you to write cleaner code in tests.

Thanks for showing interest @scottming

**Comment by scottming** [comment]
Hi, @wolfiton, I'm working on it, but I'm new to Elixir macro, I didn't know how to access the attribute dynamically.

```elixir
  defmacro query_gql_by(query_name, options \\ []) do
    quote do
      attribute = Module.get_attribute(unquote(__CALLER__.module), unquote(query_name))

      if is_nil(attribute) do
        raise WormwoodSetupError, reason: :missing_declaration
      end

      Absinthe.run(
        attribute,
        @_wormwood_gql_schema,
        unquote(options)
      )
    end
  end
```

This code will give me an error:


```elixir
ArgumentError) could not call Module.get_attribute/2 because the module AwBackendWeb.Schema.Mutation.Project.ProjectTest is already compiled. Use the Module.__info__/1 callback or Code.fetch_docs/1 instead
```

**Comment by wolfiton** [comment]
> Hi, @wolfiton, I'm working on it, but I'm new to Elixir macro, I didn't know how to access the attribute dynamically.
> 
> ```elixir
>   defmacro query_gql_by(query_name, options \\ []) do
>     quote do
>       attribute = Module.get_attribute(unquote(__CALLER__.module), unquote(query_name))
> 
>       if is_nil(attribute) do
>         raise WormwoodSetupError, reason: :missing_declaration
>       end
> 
>       Absinthe.run(
>         attribute,
>         @_wormwood_gql_schema,
>         unquote(options)
>       )
>     end
>   end
> ```
> 
> This code will give me an error:
> 
> ```elixir
> ArgumentError) could not call Module.get_attribute/2 because the module AwBackendWeb.Schema.Mutation.Project.ProjectTest is already compiled. Use the Module.__info__/1 callback or Code.fetch_docs/1 instead
> ```

Hi @scottming,
I haven't worked with macros my interest is phoenix absinthe and web dev. So I was busy with that part.
But from the error that you got, it seems that you can use Module.info to get more info. 
Also, you can await a response from tinfoil security team, they are the creators of the project so they must definetely know what you can do.

On the other hand you can create a new issue for a contributing guide, to help everyone that wants in the fututre to help move this project forward.

**Comment by wolfiton** [comment]
Hi @scottming,

One other idea could be to head to elixirforum.com and post your question there.

Here is the link https://elixirforum.com/

**Comment by wolfiton** [comment]
Also Free weekend on VueMastery link is here https://www.vuemastery.com/free-weekend/
Any course is free this weekend.

I thought that somebody may find this useful, if not please delete.
Thanks

**Comment by scottming** [comment]
I've tried `Module.__info__/1 callback` and `Code.fetch_docs/1 `, they both not work.

**Comment by scottming** [comment]
Hi, @wolfiton, @QuinnWilton , I've done the pr: 
https://github.com/tinfoil/wormwood/pull/16

**Comment by wolfiton** [comment]
> Hi, @wolfiton, @QuinnWilton , I've done the pr:
> #16

Great @scottming , we will have to wait for tinfoil security to review your pr and add it to the main library.

One question though, have you created a test for the part that you want to contribute?

**Comment by scottming** [comment]
@wolfiton Yes, I just added, but I don't know if the scope of the tests is wide enough.

**Comment by wolfiton** [comment]
Don't worry they will also review it before it's added to the main library. They are super nice guys

**Comment by moperacz** [comment]
any news on this? the PR is working perfectly... and some time has passed...

**Comment by wolfiton** [comment]
Hi, @moperacz 

You should contact https://www.tinfoilsecurity.com/ directly using the bubble for help from the site and send them an email.
I am also curious if this feature can be added and closed.

**Comment by moperacz** [comment]
@wolfiton ty! did exactly that

**Comment by uhrobots** [comment]
Hey everyone! I've gone and merged that PR, thank you so much for the contribution and for your patience!

**Comment by uhrobots** [comment]
And it's been published to Hex 😃

**Comment by wolfiton** [comment]
> @wolfiton ty! did exactly that

You are welcome, glad I could help

**Comment by wolfiton** [comment]
> Hey everyone! I've gone and merged that PR, thank you so much for the contribution and for your patience!

Thanks for the quick response the merge and the whole library

**Comment by BlueHotDog** [comment]
hey all, thank you for the awesome lib!
Justed wanted to say that this version isnt actually on hex.. 1.1.2(latest on hex) doesnt include this.

**Comment by uhrobots** [comment]
Oh my! Thank you for pointing that out. I'll try and get a release out this afternoon!
